#!/bin/bash

# detect interactive or non-interactive running of the script
if tty 2>&1 > /dev/null ; then
        INTERACTIVE="-it"
else
        INTERACTIVE=""
        echo "No terminal detected, running in non-interactive mode"
fi

IMAGE="bassel/web-app"
USERID=$(id -u)
GROUPID=$(id -g)
# internal mountpoint. DO NOT CHANGE!
WORKDIR="/usr/node-app"
RUNCOMMAND="docker"
RUNPARAMETERS=("run" $INTERACTIVE "--rm" -v "$(pwd):$WORKDIR" "$IMAGE" "npm" "run" "build")

$RUNCOMMAND "${RUNPARAMETERS[@]}"